--
-- TOC entry 10 (class 2615 OID 16441)
-- Name: tags; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tags;


--
-- TOC entry 208 (class 1255 OID 16495)
-- Name: tag_table_updated(); Type: FUNCTION; Schema: tags; Owner: -
--

CREATE FUNCTION tags.tag_table_updated() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;


--
-- TOC entry 209 (class 1255 OID 16509)
-- Name: tag_value_table_updated(); Type: FUNCTION; Schema: tags; Owner: -
--

CREATE FUNCTION tags.tag_value_table_updated() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;


--
-- TOC entry 200 (class 1259 OID 16484)
-- Name: tag_id_seq; Type: SEQUENCE; Schema: tags; Owner: -
--

CREATE SEQUENCE tags.tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 201 (class 1259 OID 16486)
-- Name: tag; Type: TABLE; Schema: tags; Owner: -
--

CREATE TABLE tags.tag (
    id bigint DEFAULT nextval('tags.tag_id_seq'::regclass) NOT NULL,
    owner character varying(255) NOT NULL,
    type smallint DEFAULT 0 NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp(6) with time zone DEFAULT now(),
    updated_at timestamp(6) with time zone
);


--
-- TOC entry 2859 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN tag.id; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag.id IS 'The table primary key - autogenerated by sequence.';


--
-- TOC entry 2860 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN tag.owner; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag.owner IS 'Owner email address - should be taken from access token.';


--
-- TOC entry 2861 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN tag.type; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag.type IS 'Tag type (0-string, 1-number, 2-boolean, 3-date, 4-time, 5-datetime)';


--
-- TOC entry 2862 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN tag.name; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag.name IS 'Tag name';


--
-- TOC entry 2863 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN tag.created_at; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag.created_at IS 'Record created timestamp - default now.';


--
-- TOC entry 2864 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN tag.updated_at; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag.updated_at IS 'Record updated timestamp - updated by trigger/function.';


--
-- TOC entry 202 (class 1259 OID 16499)
-- Name: tag_value_id_seq; Type: SEQUENCE; Schema: tags; Owner: -
--

CREATE SEQUENCE tags.tag_value_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 203 (class 1259 OID 16501)
-- Name: tag_value; Type: TABLE; Schema: tags; Owner: -
--

CREATE TABLE tags.tag_value (
    id bigint DEFAULT nextval('tags.tag_value_id_seq'::regclass) NOT NULL,
    tag_id bigint NOT NULL,
    owner character varying(255) NOT NULL,
    value character varying(255) NOT NULL,
    created_at timestamp(6) with time zone DEFAULT now(),
    updated_at timestamp(6) with time zone
);


--
-- TOC entry 2865 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN tag_value.id; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag_value.id IS 'The table primary key - autogenerated by sequence.';


--
-- TOC entry 2866 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN tag_value.tag_id; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag_value.tag_id IS 'The table foreign key to tags.tag.id.';


--
-- TOC entry 2867 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN tag_value.owner; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag_value.owner IS 'Owner email address - should be taken from access token.';


--
-- TOC entry 2868 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN tag_value.value; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag_value.value IS 'Tag value';


--
-- TOC entry 2869 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN tag_value.created_at; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag_value.created_at IS 'Record created timestamp - default now.';


--
-- TOC entry 2870 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN tag_value.updated_at; Type: COMMENT; Schema: tags; Owner: -
--

COMMENT ON COLUMN tags.tag_value.updated_at IS 'Record updated timestamp - updated by trigger/function.';


--
-- TOC entry 2727 (class 2606 OID 16498)
-- Name: tag tag_pkey; Type: CONSTRAINT; Schema: tags; Owner: -
--

ALTER TABLE ONLY tags.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);


--
-- TOC entry 2729 (class 2606 OID 16512)
-- Name: tag_value tag_value_pkey; Type: CONSTRAINT; Schema: tags; Owner: -
--

ALTER TABLE ONLY tags.tag_value
    ADD CONSTRAINT tag_value_pkey PRIMARY KEY (id);


--
-- TOC entry 2731 (class 2620 OID 16496)
-- Name: tag tags_tag_updated; Type: TRIGGER; Schema: tags; Owner: -
--

CREATE TRIGGER tags_tag_updated BEFORE UPDATE ON tags.tag FOR EACH ROW EXECUTE PROCEDURE tags.tag_table_updated();


--
-- TOC entry 2732 (class 2620 OID 16510)
-- Name: tag_value tags_tag_value_updated; Type: TRIGGER; Schema: tags; Owner: -
--

CREATE TRIGGER tags_tag_value_updated BEFORE UPDATE ON tags.tag_value FOR EACH ROW EXECUTE PROCEDURE tags.tag_value_table_updated();


--
-- TOC entry 2730 (class 2606 OID 16513)
-- Name: tag_value value_tag_fkey; Type: FK CONSTRAINT; Schema: tags; Owner: -
--

ALTER TABLE ONLY tags.tag_value
    ADD CONSTRAINT value_tag_fkey FOREIGN KEY (tag_id) REFERENCES tags.tag(id);


-- Completed on 2018-11-30 10:20:06

--
-- PostgreSQL database dump complete
--

